version: '3'

services:
  postgres:
    container_name: postgres-db
    image: postgres:14
    ports:
      - '5432:5432'
    restart: unless-stopped
    volumes:
      - ./postgres:/var/lib/postgresql/data
    env_file:
      - '.env'
  redis:
    container_name: redis-db
    image: redis:7
    command: >
      --requirepass ${REDIS_PASSWORD}
    ports:
      - '6379:6379'
    restart: unless-stopped
    env_file:
      - '.env'
